[nacos_service_config]
server_addr = "127.0.0.1:8848"
username = "xxx"
password = "xxx"
namespace = "id"

[translator_config]
libre_translate = { api = "http://127.0.0.1:5000/translate" }
# or
# open_ai = { keys = ["sk-xxxxxxxxxxx"] }

[models_config]
model_path = "/opt/vpc/models"
model_memory_path = "/dev/shm/models"

# GB
checkpoints_memory_limit = 50
loras_memory_limit = 50
