[nacos_service_config]
server_addr = "127.0.0.1:8848"
username = "xxx"
password = "xxx"
namespace = "id"

[translator_config]
api = "http://127.0.0.1:5000/translate"

#todo 提前创建目录, 移除初始化默认下载模型逻辑
[models_config]
memory_disk_path = ""

# Lazy load
checkpoints = ""
# GB
checkpoints_memory_limit = 50
loras = ""
loras_memory_limit = 50

# Eager load
embeddings = ""
vae_approx = ""
upscale_models = ""
inpaint = ""
controlnet = ""
clip_vision = ""
fooocus_expansion = ""