name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install maturin
          maturin build --release
          commit = ${{ github.sha }}
          gh release create ${commit:0:16} target/wheels/*.whl
        env:
          GH_TOKEN: ${{ github.token }}