name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install maturin
          maturin build --release
          gh release create ${{ github.sha }} target/wheels/*.whl
        env:
          GH_TOKEN: ${{ github.token }}