name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install maturin
          maturin build --release
          commit=${{ github.sha }}
          gh release create ${commit:0:16} target/wheels/*.whl
        env:
          GH_TOKEN: ${{ github.token }}