name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install maturin
          maturin build --release
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels/*.whl

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: download
      - run: |
          commit=${{ github.sha }}
          gh release create ${commit:0:16} download/*.whl
        env:
          GH_TOKEN: ${{ github.token }}